@startuml F011_kontoAnmelden_seq
title "Konto anmelden"

actor "Nutzer" as user
boundary "Anmeldung Maske" as signInMask
actor "Anmeldung Controller" as controller
database "Datenbank" as db

user -> signInMask: Eingabe E-Mail-Adresse + Passwort
activate user
user -> signInMask: Betätige Anmeldung-Button
signInMask -> controller: Übermittlung E-Mail-Adresse + Passwort

controller -> db: Ermitteln Passwort-Hash für Nutzer mit E-Mail-Adresse 
activate controller
controller <-- db: Passwort-Hash für Nutzer mit E-Mail-Adresse
controller -> controller: Hash von übermitteltem Passwort erstellen und vergleichen

controller -> controller: JSON Web Token generieren

signInMask <-- controller: Übermittlung JSON Web Token
deactivate controller

signInMask -> signInMask: Speichere JSON Web Token in Local Storage
user <-- signInMask: Bestätige erfolgte Anmeldung
deactivate user
@enduml