@startuml F015_kontoLoeschen_seq
title "Konto löschen"

actor "Angemeldeter Nutzer" as user
boundary "Konto löschen Maske" as deleteUserMask
actor "Konto löschen Controller" as controller
database "Datenbank" as db

user -> deleteUserMask: Betätige Konto löschen Knopf
activate user
user <-- deleteUserMask: Fordere Passwort an
user -> deleteUserMask: Eingabe Passwort
user <-- deleteUserMask: Aktiviere Konto löschen Formular-senden Knopf
user -> deleteUserMask: Betätige Konto löschen Formular-senden Knopf
user <-- deleteUserMask: Nachfragen ob Konto tatsächlich gelöscht werden soll
user -> deleteUserMask: Bestätige Konto tatsächlich gelöscht werden Knopf

deleteUserMask -> controller: Übermittle Löschen-Anfrage mit Passwort für angemeldeten Benutzer
activate controller
controller -> db: Ermittle Passwort Hash für angemeldeten Benutzer
controller <-- db: Passwort Hash für angemeldeten Benutzer
controller -> controller: Passwort-Hash für altes übermitteltes Passwort erstellen und mit gespeichertem Hash vergleichen
controller -> db: Lösche sämtliche mit E-Mail Adresse in Verbindung stehende Daten
controller <-- db: Bestätige Löschung der Daten
deleteUserMask <-- controller: Informiere über Löschung des Kontos
deactivate controller

deleteUserMask -> deleteUserMask: Lösche lokale Nutzerdaten (JSON Web Token, ...)
user <-- deleteUserMask: Zeige "Konto gelöscht" Bestätigung
deactivate user
@enduml