@startuml F019_KalendereintragExportieren_act
<style file=plantStyle.css>
title "Kalendereintrag exportieren"

|Event-Teilnehmer|
start
:Event-Übersicht öffnen;
:"Kalendereintrag exportieren" Knopf von teilgenommenem Event anklicken;
:Kalendereintrag exportieren Anfrage senden;
|Kalendereintrag exportieren Controller|
:Kalendereintrag exportieren Anfrage empfangen;
:Kalendereintrag incl. .ics Datei erstellen;
'TODO via E-Mail klären?
:Kalendereintrag via E-Mail an Nutzer senden;
|Event-Teilnehmer|
:Kalendereintrag via E-Mail empfangen;
stop
@enduml