@startuml F019_KalendereintragExportieren_seq
title "Kalendereintrag exportieren"

boundary "Event-Zusage/Event-Änderung Controller" as eventController
actor "Kalendereintrag exportieren Controller" as calendarController
database "Datenbank" as db
boundary "Event-Teilnehmer Email" as userMail
actor "Event-Teilnehmer" as user

eventController -> calendarController: Kalendereintrag exportieren Anfrage senden
activate calendarController
calendarController -> db: Kalendereintrag exportieren Information ermitteln
calendarController <-- db: Kalendereintrag exportieren Information
calendarController -> calendarController: Kalendereintrag exportieren Information zusammenstellen (incl. .ics Datei)
calendarController -> userMail: Kalendereintrag exportieren Information senden
deactivate calendarController
userMail --> user: Kalendereintrag exportieren Information empfangen
activate user
user -> userMail: Kalendereintrag exportieren Information öffnen
user <-- userMail: Kalendereintrag exportieren Information anzeigen
deactivate user
@enduml