@startuml F018_WegbeschreibungZumEvent_act
<style file=../../plantStyle.css>
title "Wegbeschreibung zum Event"

|Event-Teilnehmer|
start
:Event-Übersicht öffnen;
:"Wegbeschreibung" Knopf von Event an dem teilgenommen wird anklicken;
:Adresse des Events anfordern;
|Event Controller|
:Event ermitteln;
if () then (Event nicht gefunden)
    :Fehlermeldung senden;
    |Event-Teilnehmer|
    :Fehlermeldung anzeigen;
    stop
else (Event gefunden)
endif
|Event Controller|
:Adresse übermitteln;
|Event-Teilnehmer|
:Adresse empfangen;
:Wegbeschreibung anzeigen;
note right
    Screenshot 1
end note
stop
@enduml