@startuml F017_BenachrichtigungenZumEvent_seq
title "Benachrichtigungen zum Event"

boundary "Event-Änderung/Event-Absage Controller" as eventController
database "Datenbank" as db
boundary "Event-Teilnehmer Email" as userMail
actor "Event-Teilnehmer" as user

activate eventController
eventController -> db: Informationen über geändertes Event anfragen
eventController <-- db: Informationen über geändertes Event
eventController -> eventController: Informationen über geändertes Event zusammenstellen
eventController -> userMail: Informationen über geändertes Event an Teilnehmer senden
deactivate calendarController
userMail --> user: Informationen über geändertes Event liegen vor
activate user
user -> userMail: Informationen über geändertes Event öffnen
user <-- userMail: Informationen über geändertes Event anzeigen
deactivate user
@enduml