spring:
  application:
    name: party-time
  datasource:
    url: jdbc:h2:file:./.runtime-files/database.h2
    username: sa
    password: partytime
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database: h2
    defer-datasource-initialization: true
  web:
    locale: en
    locale-resolver: fixed
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  web:
    locale: en
    locale-resolver: fixed
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
