spring:
  application:
    name: party-time
  datasource:
    url: jdbc:h2:file:./.runtime-files/database.h2
    username: sa
    password: partytime
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database: h2
  h2:
    console:
      enabled: true
  web:
    locale: de
    locale-resolver: fixed
  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: lucas@dangl.io
    password: 5J6fBw3zRADv0n7C
  mustache:
    prefix: classpath:/mail/
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
party-time:
  url: http://localhost:4200
  mail:
    enabled: false
server:
  port: 8090
