@startuml F018_WegbeschreibungZumEvent_act
<style file=plantStyle.css>
title "Wegbeschreibung zum Event"

|Teilnehmer|
start
:Event-Übersicht öffnen;
:"Wegbeschreibung" Knopf von Event an dem teilgenommen wird anklicken;
:Wegbeschreibung erhalten;
stop
@enduml