@startuml F018_WegbeschreibungZumEvent_seq
title "Wegbeschreibung zum Event"

actor "Event-Teilnehmer" as user
boundary "Event-Übersicht Maske" as eventMask
boundary "Navigation Anbieter" as navProvider

user -> eventMask: "Wegbeschreibung" Knopf anklicken
activate user
eventMask -> navProvider: Wegbeschreibung anfordern
user <-- navProvider: Wegbeschreibung anzeigen
deactivate user
@enduml