@startuml F007_einladungErhalten_act
<style file=../../plantStyle.css>
title "Einladung erhalten"

|Gast einladen Controller|
start
:Einladung via E-Mail an Gast senden;
|Eingeladener Gast|
:Einladung via E-Mail empfangen;
:Einladung via E-Mail öffnen;
:Einladung auf "Einladungen" Webseite sehen;
note right
    Screenshot 1
end note
stop
@enduml