@startuml F007_einladungErhalten_seq
title "Einladung erhalten"

actor "Einladung Controller" as controller
database "Datenbank" as db
boundary "Nutzer Email" as userMail
actor "Eingeladener Nutzer" as user
boundary "Einladungen Maske" as inviteMask

controller -> userMail: Einladung verschicken
activate controller
activate userMail
controller <-- userMail: Rückmeldung: hat Einladung empfangen
par
controller -> db: Einladung speichern
controller <-- db: Einladung gespeichert
deactivate controller
else
userMail --> user: Einladung Email erhalten
activate user
userMail <- user: Einladung Email öffnen
userMail --> user: Einladung Email anzeigen
deactivate userMail
user -> inviteMask: Einladungen öffnen
activate inviteMask
user <-- inviteMask: Einladungen anzeigen
deactivate inviteMask
deactivate user
end
@enduml