@startuml F009_absageZumEventGeben_act
<style file=../../plantStyle.css>
title "Absage zum Event geben"

|Eingeladener Nutzer|
start
:Absagen-Link in E-Mail anklicken;
:Absage Webseite öffnen;
:Absage senden;
|Einladung Controller|
:Absage empfangen;
:Absage validieren;
if () then (Validieren nicht erfolgreich)
    :Fehlermeldung senden;
    |Eingeladener Nutzer|
    :Fehlermeldung Absage empfangen;
    :Fehlermeldung Absage anzeigen;
    stop
else (Validieren erfolgreich)
endif
|Einladung Controller|
:Absage speichern;
:Absage bestätigen;
|Eingeladener Nutzer|
:Bestätigung der Absage empfangen;
:Bestätigung der Absage anzeigen;
note right
    Screenshot 1
end note
stop
@enduml