@startuml F014_kontoVerifizieren_act
<style file=../../plantStyle.css>
title "Konto verifizieren"

|Verifizieren Controller|
start
:Verifizierung-Token für Nutzer generieren;
:Verifizierung-Token an Nutzer via E-Mail senden;
|Nutzer|
:Verifizierung-Token via E-Mail empfangen;
if () then (Verifizieren via Link)
    :Verifizieren Link anklicken;
    :Verifizieren Webseite öffnet sich;
else (Verifiziere via Code-Eingabe)
    :Verifizieren Webseite öffnen;
    repeat
        repeat
            :Verifizierung-Token in Webseite eintragen;
            note right
                Screenshot 1
            end note
            |Frontend Validator|
            :Eingabefeld gefüllt prüfen;
            backward:Leeres Eingabefeld markieren;
        repeat while () is (Eingabefeld leer) not (Eingabefeld gefüllt)
        backward:Formell falschen Verifizierung-Token markieren;
        :Eingabefeld formell prüfen;
    repeat while () is (Eingabe formell falsch) not (Eingabe formell richtig)
endif
|Nutzer|
: Verifizierung-Token an Backend übermitteln;
|Verifizieren Controller|
:Validität Verifizierung Code prüfen;
if () then (Verifizierung-Token zulässig)
    |Verifizieren Controller|
    :Verifikation der E-Mail des Benutzers persistieren;
    :Sende Bestätigung an Nutzer;
    |Nutzer|
    : Bestätigung empfangen und anzeigen;
    note right
        Screenshot 2
    end note
    stop
    
else (Verifizierung-Token unzulässig)
    |Verifizieren Controller|
    :Sende Fehlermeldung an Frontend;
    |Nutzer|
    :Fehlermeldung empfangen und anzeigen;
    stop;
@enduml