@startuml F002_eventsBearbeiten_seq
title "Events bearbeiten"

actor "Veranstaltender Nutzer" as user
boundary "Event bearbeiten Maske" as editEvent
control "Frontend Validator" as frontValid
actor "Event bearbeiten Controller" as controller
database "Datenbank" as db

user -> editEvent: Bearbeitung Eventname + Adresszeile (Straße und Hausnummer) + Postleitzahl + Ort + Land + Uhrzeit + Datum
activate user
editEvent -> frontValid: Validiere Eventname + Adresszeile (Straße und Hausnummer) + Postleitzahl + Ort + Land + Uhrzeit + Datum
editEvent <-- frontValid: Eventname + Adresszeile (Straße und Hausnummer) + Postleitzahl + Ort + Land + Uhrzeit + Datum valide
user <-- editEvent: Aktiviere Senden-Knopf
user -> editEvent: Sende Event-bearbeiten-Formular

editEvent -> controller: Übermittle Eventname + Adresszeile (Straße und Hausnummer) + Postleitzahl + Ort + Land + Uhrzeit + Datum
activate controller
controller -> controller: Eventdaten serverseitig verifizieren
controller -> db: Speichere geänderten Eventname + Adresszeile (Straße und Hausnummer) + Postleitzahl + Ort + Land + Uhrzeit + Datum
controller <-- db: Bestätige Speicherung
editEvent <-- controller: Bestätige Eventbearbeitung
deactivate controller

user <-- editEvent: Zeige Eventbearbeitung-Bestätigung
deactivate user
@enduml