@startuml F003_eventsLoeschen_seq
title "Events löschen"

actor "Veranstaltender Nutzer" as user
boundary "Event löschen Maske" as deleteEventMask
actor "Event löschen Controller" as controller
database "Datenbank" as db

user -> deleteEventMask: Klicke Button für Event löschen
activate user
user <-- deleteEventMask: Frage ob Event wirklich gelöscht werden soll
user -> deleteEventMask: Bestätige tatsächliche Löschung des Events
deleteEventMask -> controller: Übermittle Event löschen Anfrage
activate controller
controller -> db: Eventdaten löschen
controller <-- db: Bestätige Löschung der Eventdaten
deleteEventMask <-- controller: Bestätige Löschung des Events
deactivate controller

user <-- deleteEventMask: Zeige Eventlöschung-Bestätigung
deactivate user
@enduml