@startuml F010_kontoErstellen
title "Konto erstellen"

actor "Nutzer" as user
boundary "Registration Maske" as reg
control "Frontend Validator" as frontValid
actor "Registration Controller" as controller
database "Datenbank" as db

' Initiale Registrierung
user -> reg: Eingabe Anzeigename + E-Mail-Adresse + Passwort
activate user
reg -> frontValid: Validiere Anzeigename + E-Mail-Adresse + Passwort
reg <-- frontValid: Anzeigename + E-Mail-Adresse + Passwort valide
user <-- reg: Aktiviere Senden-Knopf
user -> reg: Sende Registration-Formular

reg -> controller: Übermittle Anzeigename + E-Mail-Adresse + Passwort
activate controller
controller -> db: Prüfe E-Mail-Adresse noch nicht in Verwendung
controller <-- db: E-Mail-Adresse noch nicht verwendet
controller -> controller: Passwort-Hash erstellen
controller -> db: Speichere Anzeigename + E-Mail + Passwort-Hash
controller <-- db: Bestätige Speicherung
reg <-- controller: Bestätige Registrierung
deactivate controller

user <-- reg: Zeige Registrierung-Bestätigung
deactivate user
@enduml