@startuml F012_kontoAbmelden
title "Konto abmelden"

actor "Nutzer" as user
boundary "Abmelden Maske" as userMask

user -> userMask: Betätige Abmelden Knopf
activate user
userMask -> userMask: Lösche JSON Web Token in Local Storage
user <-- userMask: Bestätige erfolgte Anmeldung
deactivate user
@enduml