@startuml F014_kontoVerifizieren
title "Konto verifizieren"

actor "Validierung Controller" as controller
database "Datenbank" as db
boundary "Email-Validierung Webseite" as signupConfirm
boundary "Nutzer Email" as userMail
actor "Nutzer" as user


'E-Mail Validierung
controller -> db: Speichere neuen JSON Web Token jit für Nutzer
controller <-- db: Bestätige JSON Web Token jit Speicherung
controller -> controller: Generiere Validierung JSON Web Token mit jit
userMail <- controller: Sende Validierung-Link mit JSON Web Token
deactivate controller

userMail -> user: Informiere neue E-Mail
activate user
userMail <-- user: Prüfe Mail
userMail -> signupConfirm: Öffne verlinkte Email-Validierung Webseite mit JSON Web Token
signupConfirm -> controller: Bestätige Validität mit JSON Web Token verknüpfter E-Mail-Adresse
activate controller
controller -> db: Prüfe Validität JSON Web Token jit
controller <-- db: Bestätige JSON Web Token jit Validität
controller -> db: Lösche JSON Web Token jit
controller <-- db: Bestätige JSON Web Token jit Löschung
controller -> db: Speichere E-Mail Validität
controller <-- db: Bestätige Speicherung E-Mail Validität
signupConfirm <-- controller: Bestätige E-Mail Validität
deactivate controller

user <-- signupConfirm: Bestätige Konto-Verifizierung
deactivate user
@enduml