@startuml F015_kontoLoeschen
title "Konto löschen"

actor "Angemeldeter Nutzer" as user
boundary "Konto löschen Maske" as deleteUserMask
actor "Konto löschen Controller" as controller
database "Datenbank" as db

user -> deleteUserMask: Betätige Konto löschen Knopf
activate user
user <-- deleteUserMask: Nachfragen ob Konto tatsächlich gelöscht werden soll
user -> deleteUserMask: Betätige tatsächliches Konto löschen

deleteUserMask -> controller: Übermittle Session Token
activate controller
controller -> db: Ermittle E-Mail Adresse für Session Token
controller <-- db: E-Mail Adresse für Session Token
controller -> db: Lösche sämtliche mit E-Mail Adresse in Verbindung stehende Daten
controller <-- db: Bestätige Löschung der Daten
deleteUserMask <-- controller: Informiere über Löschung des Kontos
deactivate controller

deleteUserMask -> deleteUserMask: Lösche lokale Nutzerdaten (Cookies, ...)
user <-- deleteUserMask: Zeige Konto gelöscht Info
deactivate user
@enduml