@startuml F015_kontoLoeschen
title "Konto löschen"

actor "Angemeldeter Nutzer" as user
boundary "Konto löschen Maske" as deleteUserMask
actor "Konto löschen Controller" as controller
database "Datenbank" as db

user -> deleteUserMask: Betätige Konto löschen Knopf
activate user
user <-- deleteUserMask: Nachfragen ob Konto tatsächlich gelöscht werden soll
user -> deleteUserMask: Betätige tatsächliches Konto löschen

deleteUserMask -> controller: Übermittle Löschen-Anfrage mit JSON Web Token
activate controller
controller -> db: Lösche sämtliche mit E-Mail Adresse in Verbindung stehende Daten
controller <-- db: Bestätige Löschung der Daten
deleteUserMask <-- controller: Informiere über Löschung des Kontos
deactivate controller

deleteUserMask -> deleteUserMask: Lösche lokale Nutzerdaten (JSON Web Token, ...)
user <-- deleteUserMask: Zeige "Konto gelöscht" Information
deactivate user
@enduml