@startuml F013_passwortAendern_seq
title "Passwort ändern"

actor "Angemeldeten Nutzer" as user
boundary "Passwort ändern Maske" as changePwd
control "Frontend Validator" as frontValid
actor "Passwort ändern Controller" as controller
database "Datenbank" as db

' Initiale Registrierung
user -> changePwd: Eingabe altes + neues Passwort
activate user
changePwd -> frontValid: Validiere neues Passwort
changePwd <-- frontValid: neues Passwort valide
user <-- changePwd: Aktiviere Senden-Knopf
user -> changePwd: Sende Passwort ändern Formular

changePwd -> controller: Übermittle altes und neues Passwort + JSON Web Token
activate controller
controller -> db: Ermittle Passwort Hash für E-Mail Adresse
controller <-- db: Passwort Hash für E-Mail-Adresse
controller -> controller: Passwort-Hash für altes übermitteltes Passwort erstellen und mit gespeichertem Hash vergleichen
controller -> controller: Hash von neuem Passwort erstellen
controller -> db: Speichere neuen Passwort Hash für angemeldeten Benutzer
controller <-- db: Bestätige Speicherung des neuen Passworts
changePwd <-- controller: Bestätige Passwort Änderung
deactivate controller

user <-- changePwd: Zeige Passwort Änderung Bestätigung
deactivate user
@enduml