@startuml F013_passwortAendern_act
<style file=plantStyle.css>
title "Passwort ändern"

|Angemeldeter Nutzer|
start
:Öffne Party Time "Passwort ändern" Webseite;
repeat
    repeat
        split
            :Altes Passwort eingeben;
        split again
            :Neues Passwort eingeben;
        end split
        |Frontend Validator|
        :Prüfe altes Passwort eingegeben;
        backward:Leeres altes Passwort Feld markieren;
    repeat while () is (Altes Passwort nicht eingegeben) not (Altes Passwort eingegeben)
    :Prüfe neues Passwort;
    backward: Fehlerhaftes neues Passwort markieren;
    note right
        pw_required: Passwort nicht angegeben
        pw_short: Passwort kürzer als 8 Zeichen
        pw_long: Passwort länger als 30 Zeichen
        pw_wrong_chars: Zeichen nicht wie gefordert verwendet
    end note
repeat while () is (Neues Passwort fehlerhaft) not (Neues Passwort fehlerfrei)
|Angemeldeter Nutzer|
:Passwort ändern Formular senden;
|Registration Controller|
:Gespeicherten Passwort Hash für angemeldeten Nutzer ermitteln;
:Altes übermitteltes Passwort hashen und mit gespeichertem Passwort vergleichen;
if () then (Hash altes Passwort und gespeicherter Passwort Hash gleich)
    :Prüfe neues Passwort;
    if () then (Neues Passwort fehlerfrei)
    :Hashe neues Passwort;
    :Speichere Hash von neuem Passwort;
    :Bestätige Passwort Änderung;
    |Angemeldeter Nutzer|
    :Zeige "Passwort Änderung erfolgreich" Meldung;
    stop
    else (Übermittelter und gespeicherter Hash nicht gleich)
    endif
else (Hash altes Passwort und gespeicherter Passwort Hash ungleich)
endif
|Registration Controller|
:Übermittle Fehlermeldung;
|Angemeldeter Nutzer|
:Zeige "Passwort Änderung fehlgeschlagen" Meldung;
stop
@enduml