@startuml F010_kontoErstellen_act
<style file=plantStyle.css>
title "Konto erstellen"

|Nutzer|
start
:Öffne Party Time Webseite;
repeat
    repeat
        repeat
            split
                :Anzeigenamen eingeben;
            split again
                :E-Mail Adresse eingeben;
            split again
                :Passwort eingeben;
            end split
            |Frontend Validator|
            :Prüfe Anzeigenamen;
            backward:Fehlerhaften Anzeigenamen markieren;
            note right
            test_user_too_short: Benutzername kürzer als 5 Zeichen
            test_user_too_long: Benutzername länger als 20 Zeichen
            end note
        repeat while () is (Anzeigename fehlerhaft) not (Anzeigename fehlerfrei)
        :Prüfe E-Mail Adresse;
        backward:Fehlerhafte E-Mail Adresse markieren;
        note right
            test_mail_invalid: E-Mail Adresse ungültig
        end note
    repeat while () is (E-Mail Adresse fehlerhaft) not (E-Mail Adresse fehlerfrei)
    :Prüfe Passwort;
    backward: Fehlerhaftes Passwort markieren;
    note right
        test_pw_short: Passwort kürzer als 8 Zeichen
        test_pw_long: Passwort länger als 30 Zeichen
        test_pw_symbols: Sonderzeichen nicht wie gefordert verwendet
    end note
repeat while () is (Passwort fehlerhaft) not (Passwort fehlerfrei)
|Nutzer|
:Registration-Formular senden;
|Registration Controller|
:E-Mail-Adresse in Verwendung prüfen;
if () then (E-Mail Adresse in Verwendung)
    |Registration Controller|
    :Übermittle "E-Mail Addresse bereits in Verwendung" Fehlermeldung;
    |Nutzer|
    :Empfange Fehlermeldung;
    :Zeige Fehlermeldung;
    note right
        test_mail_in_use: E-Mail Adresse bereits registriert
    end note
    stop
else (E-Mail Adresse nicht in Verwendung)
    |Registration Controller|
    :Passwort hashen;
    :Anzeigename + E-Mail Adresse + Passwort-Hash speichern;
    :Bestätige Registrierung;
    |Nutzer|
    :Empfange Bestätigung der Registrierung;
    :Zeige Bestätigung der Registrierung;
    note right
        test_registration_success: Registrierung erfolgreich
    end note
    stop
endif
@enduml