@startuml F016_eventsUeberblicken_seq
title "Events überblicken"

actor "Angemeldeter Nutzer" as user
boundary "Events Überblicken Maske" as eventsUeberblickenMask
actor "Events überblicken Controller" as controller
database "Datenbank" as db

user -> eventsUeberblickenMask: Öffne Party Time "Events überblicken" Webseite
activate user
eventsUeberblickenMask --> controller: Sende automatische "Events überblicken"-Anfrage mit JSON Web Token
activate controller
user <-- eventsUeberblickenMask: Zeige "Events überblicken" Webseite ohne Event-Inhalte
controller -> db: Suche Events von Nutzer
controller <-- db: "Events überblicken " Daten
eventsUeberblickenMask <-- controller: :Sende "Events überblicken" Daten
deactivate controller
eventsUeberblickenMask -> eventsUeberblickenMask: Aktualisiere "Events überblicken" Webseite mit Event-Daten
user <-- eventsUeberblickenMask: Zeige aktualisierte "Events überblicken" Webseite
deactivate user
@enduml