@startuml F004_gaesteEinladen_seq
title "Gäste einladen"

actor "Teilnehmer überblickender veranstaltender Nutzer" as user
boundary "Teilnehmer bearbeiten Maske" as editParticipantsMask
control "Frontend Validator" as frontValid
actor "Teilnehmer einladen Controller" as controller
database "Datenbank" as db

user -> editParticipantsMask: Eingabe E-Mail Adresse einzuladender Gast
activate user
editParticipantsMask -> frontValid: Prüfe E-Mail Adresse valide
editParticipantsMask <-- frontValid: E-Mail Adresse valide
user <-- editParticipantsMask: Erlaube absenden des Formulars
user -> editParticipantsMask: Bestätige Eingabe mit Hinzufügen Button
editParticipantsMask -> controller: Übermittle E-Mail Adresse einzuladender Gast
activate controller
controller -> db: Überprüfe E-Mail Adresse noch nicht eingeladen
db --> controller: E-Mail Adresse noch nicht eingeladen
controller -> controller: Sende Einladungs-E-Mail
controller -> db: Speichere E-Mail Adresse als eingeladen
db --> controller: E-Mail Adresse als eingeladen gespeichert
controller -> editParticipantsMask: Übermittle Gasteinladung Bestätigung
deactivate controller
editParticipantsMask -> user: Zeige Gasteinladung Bestätigung
deactivate user
@enduml