@startuml F010_kontoErstellen_act
<style file=../../plantStyle.css>
title "Konto erstellen"

|Nutzer|
start
:Öffne Party Time "Registrieren" Webseite;
note right
    Screenshot 1
end note
repeat
    repeat
        repeat
            split
                :Anzeigenamen eingeben;
            split again
                :E-Mail Adresse eingeben;
            split again
                :Passwort eingeben;
            end split
            |Frontend Validator|
            :Prüfe Anzeigenamen;
            note right
                Screenshot 2
            end note
            backward:Fehlerhaften Anzeigenamen markieren;
        repeat while () is (Anzeigename fehlerhaft) not (Anzeigename fehlerfrei)
        :Prüfe E-Mail Adresse;
        backward:Fehlerhafte E-Mail Adresse markieren;
    repeat while () is (E-Mail Adresse fehlerhaft) not (E-Mail Adresse fehlerfrei)
    :Prüfe Passwort;
    backward: Fehlerhaftes Passwort markieren;
repeat while () is (Passwort fehlerhaft) not (Passwort fehlerfrei)
|Nutzer|
:Registration-Formular senden;
note right
    Screenshot 3
end note
|Registration Controller|
:E-Mail-Adresse in Verwendung prüfen;
if () then (E-Mail Adresse in Verwendung)
    |Registration Controller|
    :Übermittle "E-Mail Addresse bereits in Verwendung" Fehlermeldung;
    |Nutzer|
    :Empfange Fehlermeldung;
    :Zeige Fehlermeldung;
    stop
else (E-Mail Adresse nicht in Verwendung)
    |Registration Controller|
    :Passwort hashen;
    :Anzeigename + E-Mail Adresse + Passwort-Hash speichern;
    :Bestätige Registrierung;
    |Nutzer|
    :Empfange Bestätigung der Registrierung;
    :Zeige Bestätigung der Registrierung;
    stop
endif
@enduml