@startuml F001_eventAnlegen_act
<style file=plantStyle.css>
title "Event anlegen"

|Verifizierter Nutzer|
start
:Öffne Party Time "Event anlegen" Webseite;
repeat
    repeat
        repeat
            repeat
                repeat
                    repeat
                        repeat
                            repeat
                                split
                                    :Eventnamen eingeben;
                                split again
                                    :Adresszeile (Straße und Hausnummer) ausfüllen;
                                split again
                                    :Postleitzahl eingeben;
                                split again
                                    :Ort eingeben;
                                split again
                                    :Land eingeben;
                                split again
                                    :Uhrzeit eingeben;
                                split again
                                    :Datum eingeben;
                                end split
                                if() then (Adresszusatz soll eingegeben werden)
                                    :Adresszusatz eingeben;
                                else (Adresszusatz soll nicht eingegeben werden)
                                endif
                                |Frontend Validator|
                                :Eventnamen prüfen;
                                backward:Fehlerhaften Eventnamen markieren;
                                note right
                                    name_required: Bitte gib einen Namen für das Event ein.
                                    name_short: Der Eventname muss mindestens 5 Zeichen lang sein.
                                    name_long: Der Eventname darf maximal 30 Zeichen lang sein.
                                end note
                            repeat while () is (Eventname fehlerhaft) not (Eventname fehlerfrei)
                            :Adresszeile (Straße und Hausnummer) prüfen;
                            backward:Fehlerhafte Adresszeile (Straße und Hausnummer) markieren;
                            note right
                                address_required: Bitte gib die Straße und Hausnummer ein, wo das Event stattfinden wird.
                                address_short: Eine gültige Adresse hat mindestens 4 Stellen.
                                address_long: Eine gültige Adresse hat maximal 25 Stellen.
                            end note
                        repeat while () is (Adresszeile (Straße und Hausnummer) fehlerhaft) not (Adresszeile (Straße und Hausnummer) fehlerfrei)
                        :Postleitzahl prüfen;
                        backward: Fehlerhafte Postleitzahl markieren;
                        note right
                            zip_required: Bitte gib die Postleitzahl ein, wo das Event stattfinden wird.
                            zip_short: Eine gültige Postleitzahl hat 5 Stellen.
                            zip_long: Eine gültige Postleitzahl hat 5 Stellen.
                            zip_chars: Bitte gib eine gültige Postleitzahl ein.
                        end note
                    repeat while () is (Postleitzahl fehlerhaft) not (Postleitzahl fehlerfrei)
                    :Ort prüfen;
                    backward: Fehlerhaften Ort markieren;
                    note right
                        city_required: Bitte gib eine Stadt ein, wo das Event stattfinden wird.
                        city_short: Eine gültige Stadt hat mindestens 5 Stellen.
                        city_long: Eine gültige Stadt hat maximal 20 Stellen.
                    end note
                repeat while () is (Ort fehlerhaft) not (Ort fehlerfrei)
                :Land prüfen;
                backward: Fehlerhaftes Land markieren;
                note right
                    country_required: Bitte gib ein Land ein, wo das Event stattfinden wird.
                    country_short: Ein gültiges Land hat mindestens 3 Stellen.
                    country_long: Ein gültiges Land hat maximal 20 Stellen.
                end note
            repeat while () is (Land fehlerhaft) not (Land fehlerfrei)
            :Uhrzeit prüfen;
            backward: Fehlerhafte Uhrzeit markieren;
        repeat while () is (Uhrzeit fehlerhaft) not (Uhrzeit fehlerfrei)
        :Datum prüfen;
        backward: Fehlerhaftes Datum markieren;
    repeat while () is (Datum fehlerhaft) not (Datum fehlerfrei)
    :Adresszusatz prüfen;
    backward: Fehlerhaften Adresszusatz markieren;
repeat while () is (Adresszusatz fehlerhaft) not (Adresszusatz fehlerfrei)
|Verifizierter Nutzer|
:Event-anlegen-Formular senden;
|Event erstellen Controller|
:Eventdaten serverseitig verifizieren;

if () then (Verifizierung nicht erfolgreich)
    |Event erstellen Controller|
    :Fehlermeldung senden;
    |Verifizierter Nutzer|
    :Fehlermeldung Eventerstellung empfangen;
    :Fehlermeldung Eventerstellung anzeigen;
    stop
else (Verifizierung erfolgreich)
endif
|Event erstellen Controller|
:Eventerstellung bestätigen;
|Verifizierter Nutzer|
:Bestätigung Eventerstellung empfangen;
:Bestätigung Eventerstellung anzeigen;
note right
    create_success: Dein Event ${pt_name()} wurde erfolgreich erstellt.
end note
stop
@enduml