@startuml F011_kontoAnmelden_act
<style file=../../plantStyle.css>
title "Konto anmelden"

|Nutzer|
start
:Öffne Party Time "Anmelden" Webseite;
note right
    Screenshot 1
end note
repeat
    repeat
        split
            :E-Mail Adresse eingeben;
        split again
            :Passwort eingeben;
        end split
        |Frontend Validator|
        :Prüfe E-Mail Adresse eingegeben;
        backward:Leeres E-Mail Adresse Feld markieren;
    repeat while () is (E-Mail Adresse nicht eingegeben) not (E-Mail Adresse eingegeben)
    :Prüfe Passwort eingegeben;
    
    backward: Leeres Passwort Feld markieren;
repeat while () is (Passwort nicht eingegeben) not (Passwort eingegeben)
|Nutzer|
:Anmelden-Formular senden;
note right
    Screenshot 2
end note
|Registration Controller|
:Gespeicherten Passwort Hash für Nutzer ermitteln;
if () then (Nutzer existiert in Datenbank und Passwort Hash wurde ermittelt)
    :Hash von übermitteltes Passwort mit gespeichertem Hash vergleichen;
    if () then (Übermittelter und gespeicherter Hash gleich)
    :Generiere JSON Web Token;
    :Übermittle JSON Web Token an Benutzer;
    |Nutzer|
    :Persistiere JSon Web Token in Local Storage;
    :Zeige "Anmeldung Erfolgreich" Meldung;
    note right
        Screenshot 3
    end note
    stop
    else (Übermittelter und gespeicherter Hash nicht gleich)
    endif
else (Nutzer existiert nicht in Datenbank)
endif
|Registration Controller|
:Übermittle Fehlermeldung;
|Nutzer|
:Zeige "Anmeldung Fehler" Meldung;
stop
@enduml