@startuml F016_eventsUeberblicken_act
<style file=../../plantStyle.css>
title "Events überblicken"

|Angemeldeter Nutzer|
start
:Öffne Party Time "Events überblicken" Webseite;
note right
    Screenshot 1
end note
:Sende automatische "Events überblicken"-Anfrage mit JSON Web Token;
|Events überblicken Controller|
:Suche Events von Nutzer;
:Sende "Events überblicken" Daten;
|Angemeldeter Nutzer|
:Aktualisiere "Events überblicken" Webseiten-Inhalt;
note right
    Screenshot 2
end note
stop
@enduml