@startuml F012_kontoAbmelden_act
<style file=plantStyle.css>
title "Konto abmelden"

|Nutzer|
start
:Betätige Abmelden Knopf;
|Party Time Frontend|
:Lösche lokale Nutzerdaten (JSON Web Token, ...);
|Nutzer|
:Zeige "Abmeldung erfolgreich" Bestätigung;
stop
@enduml