@startuml F012_kontoAbmelden_seq
title "Konto abmelden"

actor "Nutzer" as user
boundary "Abmelden Maske" as userMask

user -> userMask: Betätige Abmelden Knopf
activate user
userMask -> userMask: Lösche lokale Nutzerdaten (JSON Web Token, ...)
user <-- userMask: Bestätige erfolgte Anmeldung
deactivate user
@enduml