@startuml F008_zusageZumEventGeben_act
<style file=plantStyle.css>
title "Zusage zum Event geben"

|Eingeladener Nutzer|
start
:Zusagen-Link in E-Mail anklicken;
:Zusage Webseite öffnen;
:Zusage senden;
|Einladung Controller|
:Zusage empfangen;
:Zusage validieren;
if () then (Validieren nicht erfolgreich)
    :Fehlermeldung senden;
    |Eingeladener Nutzer|
    :Fehlermeldung Zusage empfangen;
    :Fehlermeldung Zusage anzeigen;
    note right
        event_not_found: Das Event wurde nicht gefunden.
        participant_not_invited: Du bist nicht zu diesem Event eingeladen.
    end note
    stop
else (Validieren erfolgreich)
endif
|Einladung Controller|
:Zusage speichern;
:Zusage bestätigen;
|Eingeladener Nutzer|
:Bestätigung der Zusage empfangen;
:Bestätigung der Zusage anzeigen;
note right
    invite_accepted: Wir haben deine Zusage gespeichert.
end note
stop
@enduml