@startuml F008_zusageZumEventGeben_seq
title "Zusage zum Event geben"

actor "Eingeladener Nutzer auf Event-Übersicht Webseite" as user
boundary "Event-Übersicht Maske" as eventMask
actor "Einladung Controller" as controller
database "Datenbank" as db

user -> eventMask: "Zusagen" Button klicken
activate user
eventMask -> controller: Zusage Informationen senden
activate controller
controller -> db: Zusage speichern
controller <-- db: Zusage gespeichert
controller -> db: Informationen über Events des Nutzers zusammenstellen
controller <-- db: Informationen über Events des Nutzers
eventMask <-- controller: Informationen über Events des Nutzers senden
deactivate controller
user <-- eventMask: Informationen über Events des Nutzers anzeigen
deactivate user
@enduml