@startuml F002_eventsBearbeiten_act
<style file=../../plantStyle.css>
title "Events bearbeiten"

|Veranstaltender Nutzer|
start
:Öffne Party Time "Organisierte Events" Webseite;
note right
    Screenshot 1
end note
:Öffne Party Time "Event bearbeiten" Webseite von Event, für welches Nutzer Veranstalter ist;
repeat
    repeat
        repeat
            repeat
                repeat
                    repeat
                        repeat
                            repeat
                                split
                                    if () then (Eventname soll geändert werden)
                                        :Eventnamen ändern;
                                    endif
                                split again
                                    if() then (Adresszeile soll geändert werden)
                                        :Adresszeile (Straße und Hausnummer) ändern;
                                    endif
                                split again
                                    if() then (Postleitzahl soll geändert werden)
                                        :Postleitzahl ändern;
                                    endif
                                split again
                                    if() then (Ort soll geändert werden)
                                        :Ort ändern;
                                    endif
                                split again
                                    if() then (Land soll geändert werden)
                                        :Land ändern;
                                    endif
                                split again
                                    if() then (Uhrzeit soll geändert werden)
                                        :Uhrzeit ändern;
                                    endif
                                split again
                                    if() then (Datum soll geändert werden)
                                        :Datum ändern;
                                    endif
                                end split
                                if() then (Adresszusatz soll geändert werden)
                                    :Adresszusatz eingeben;
                                    note right
                                        Screenshot 2
                                    end note
                                endif
                                |Frontend Validator|
                                :Eventnamen prüfen;
                                backward:Fehlerhaften Eventnamen markieren;
                            repeat while () is (Eventname fehlerhaft) not (Eventname fehlerfrei)
                            :Adresszeile (Straße und Hausnummer) prüfen;
                            backward:Fehlerhafte Adresszeile (Straße und Hausnummer) markieren;
                        repeat while () is (Adresszeile (Straße und Hausnummer) fehlerhaft) not (Adresszeile (Straße und Hausnummer) fehlerfrei)
                        :Postleitzahl prüfen;
                        backward: Fehlerhafte Postleitzahl markieren;
                    repeat while () is (Postleitzahl fehlerhaft) not (Postleitzahl fehlerfrei)
                    :Ort prüfen;
                    backward: Fehlerhaften Ort markieren;
                repeat while () is (Ort fehlerhaft) not (Ort fehlerfrei)
                :Land prüfen;
                backward: Fehlerhaftes Land markieren;
            repeat while () is (Land fehlerhaft) not (Land fehlerfrei)
            :Uhrzeit prüfen;
            backward: Fehlerhafte Uhrzeit markieren;
        repeat while () is (Uhrzeit fehlerhaft) not (Uhrzeit fehlerfrei)
        :Datum prüfen;
        backward: Fehlerhaftes Datum markieren;
    repeat while () is (Datum fehlerhaft) not (Datum fehlerfrei)
    :Adresszusatz prüfen;
    backward: Fehlerhaften Adresszusatz markieren;
repeat while () is (Adresszusatz fehlerhaft) not (Adresszusatz fehlerfrei)
|Veranstaltender Nutzer|
:Event-bearbeiten-Formular senden;
|Event bearbeiten Controller|
:Eventdaten serverseitig verifizieren;
if () then (Verifizierung nicht erfolgreich)
    |Event bearbeiten Controller|
    :Fehlermeldung senden;
    |Veranstaltender Nutzer|
    :Fehlermeldung Eventbearbeitung empfangen;
    :Fehlermeldung Eventbearbeitung anzeigen;
    stop
else (Verifizierung erfolgreich)
endif
|Event bearbeiten Controller|
:Geänderte Eventdaten persistieren;
:Eventbearbeitung bestätigen;
|Veranstaltender Nutzer|
:Bestätigung Eventbearbeitung empfangen;
:Bestätigung Eventbearbeitung anzeigen;
note right
    Screenshot 3
end note
stop
@enduml