@startuml F006_teilnehmerUeberblicken_seq
title "Teilnehmer überblicken"

actor "Veranstaltender Nutzer" as user
boundary "Events überblicken Maske" as eventOverviewMask
boundary "Teilnehmer bearbeiten Maske" as editParticipantsMask
actor "Teilnehmerübersicht Controller" as controller
database "Datenbank" as db

user -> eventOverviewMask: "Teilnehmer bearbeiten" Button bei veranstaltetem Event anklicken
activate user
eventOverviewMask -> editParticipantsMask: "Teilnehmer bearbeiten" Maske öffnen
editParticipantsMask -> controller: Teilnehmerliste anfordern
activate controller
controller -> db: Teilnehmerliste anfordern
controller <-- db: Teilnehmerliste
editParticipantsMask <-- controller: Teilnehmerliste
deactivate controller
editParticipantsMask -> user: Teilnehmerübersicht anzeigen
@enduml